name: Build, test and distribute
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Show java version
        run: java -version

      - name: Validate checksum gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle cache wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper
      - name: Test
        run: ./gradlew testDebug testTstDebug lint
      - name: Build
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew assemTstRelease assemAccRelease assemProdRelease bundleProdRelease
      - name: Archive apks
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: |
            holder/build/outputs/apk
            verifier/build/outputs/apk
          retention-days: 5
      - name: Archive bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: |
            holder/build/outputs/bundle
            verifier/build/outputs/bundle
          retention-days: 5

  distribute:
    runs-on: ubuntu-latest
    needs: [ "build-and-test" ]

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: apks
          path: apks
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          
      - name : container ls $GITHUB_WORKSPACE
        with : { entrypoint : "/bin/sh" , args : '-c "ls -la $GITHUB_WORKSPACE/apks/holder/build/outputs/apk/tst/release/"' }
        uses : "docker://alpine:latest"
        
      - name : container ls $GITHUB_WORKSPACE
        with : { entrypoint : "/bin/sh" , args : '-c "ls -la $GITHUB_WORKSPACE/apks/holder/build/outputs/apk/acc/release/"' }
        uses : "docker://alpine:latest"
        
      - name : container ls $GITHUB_WORKSPACE
        with : { entrypoint : "/bin/sh" , args : '-c "ls -la $GITHUB_WORKSPACE/apks/holder/build/outputs/apk/prod/release/"' }
        uses : "docker://alpine:latest"
        
      - name : container ls $GITHUB_WORKSPACE
        with : { entrypoint : "/bin/sh" , args : '-c "ls -la $GITHUB_WORKSPACE/apks/verifier/build/outputs/apk/tst/release/"' }
        uses : "docker://alpine:latest"
        
      - name : container ls $GITHUB_WORKSPACE
        with : { entrypoint : "/bin/sh" , args : '-c "ls -la $GITHUB_WORKSPACE/apks/verifier/build/outputs/apk/acc/release/"' }
        uses : "docker://alpine:latest"
        
      - name : container ls $GITHUB_WORKSPACE
        with : { entrypoint : "/bin/sh" , args : '-c "ls -la $GITHUB_WORKSPACE/apks/verifier/build/outputs/apk/prod/release/"' }
        uses : "docker://alpine:latest"
          
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "$GITHUB_WORKSPACE/apks/holder/build/outputs/apk"
          target: "/"
