name: Build, test and distribute
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Show java version
        run: java -version

      - name: Validate checksum gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle cache wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper
      - name: Test
        run: ./gradlew testDebug testTstDebug lint
      - name: Write key store
        if: github.event.repository.name != 'nl-covid19-coronacheck-app-android'
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo $KEYSTORE_FILE | base64 --decode > keystore.jks
      - name: Build
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew assemTstRelease assemAccRelease assemProdRelease bundleProdRelease
      - name: Clean up key store
        if: ${{github.event.repository.name != 'nl-covid19-coronacheck-app-android'}}
        run: rm keystore.jks   
      - name: Archive apks
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: |
            holder/build/outputs/apk
            verifier/build/outputs/apk
          retention-days: 5
      - name: Archive bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: |
            holder/build/outputs/bundle
            verifier/build/outputs/bundle
          retention-days: 5
